package empleado;

import java.awt.Color;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usuario
 */
public class Interfaz extends javax.swing.JFrame {

    Empleado em5 = null;
    boolean flag = true;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        buttonGroup1.add(jRadioButtonJP);
        buttonGroup1.add(jRadioButtonTH);
        buttonGroup1.add(jRadioButtonMontador);
        buttonGroup1.add(jRadioButtoncomision);

        jLabelApell.setVisible(true);
        jLabelNombre.setVisible(true);
        jLabelComision.setVisible(false);
        jLabelSalBase.setVisible(false);
        jLabelElec.setVisible(false);

        jTextFieldApell.setVisible(true);
        jTextFieldNombre.setVisible(true);
        jTextFieldComision.setVisible(false);
        jTextFieldSalBase.setVisible(false);
        jTextFieldElec.setVisible(false);

        ArrayList<Empleado> ListaEmp = new ArrayList<Empleado>();

        Empleado em1 = new JefesDeProyectos("Luis ", "Gilarte ", 1000, 7);

        Empleado em2 = new TrabajadoresPorHoras("Javier ", "Barrios ", 70, 16);

        Empleado em3 = new Montador("Jorge ", "Castilla ", 5, 300);

        Empleado em4 = new Vendedores("Diego ", "Vicario ", 5, 30, 600);

        jListempleados.setModel(Empleado.modeloLista);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelTrabajadores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListempleados = new javax.swing.JList();
        jLabelSelec = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jButtonEliminarTrabajador = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApell = new javax.swing.JLabel();
        jTextFieldApell = new javax.swing.JTextField();
        jLabelSalBase = new javax.swing.JLabel();
        jLabelComision = new javax.swing.JLabel();
        jLabelElec = new javax.swing.JLabel();
        jTextFieldSalBase = new javax.swing.JTextField();
        jTextFieldComision = new javax.swing.JTextField();
        jTextFieldElec = new javax.swing.JTextField();
        jPanelTipos = new javax.swing.JPanel();
        jPanelTipoT = new javax.swing.JPanel();
        jRadioButtonJP = new javax.swing.JRadioButton();
        jRadioButtonTH = new javax.swing.JRadioButton();
        jRadioButtonMontador = new javax.swing.JRadioButton();
        jRadioButtoncomision = new javax.swing.JRadioButton();
        jButtonAñadir = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuarchivo = new javax.swing.JMenu();
        jMenutrabajador = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenu();
        jMenuItemJP = new javax.swing.JMenuItem();
        jMenuItemTPH = new javax.swing.JMenuItem();
        jMenuItemMontador = new javax.swing.JMenuItem();
        jMenuItemComision = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBorrTodo = new javax.swing.JMenuItem();
        jMenuItemBorrarSeleccionado = new javax.swing.JMenuItem();
        jMenuItemBorrSeleccion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTrabajadores.setBorder(javax.swing.BorderFactory.createTitledBorder("Trabajadores En Activo"));

        jListempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListempleadosMouseClicked(evt);
            }
        });
        jListempleados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListempleadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListempleados);

        jLabelSelec.setText("Selecciona un trabajador para ver su salario");

        jLabelSalario.setText("SALARIO:");

        jTextFieldSalario.setToolTipText("");
        jTextFieldSalario.setFocusable(false);
        jTextFieldSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalarioActionPerformed(evt);
            }
        });

        jButtonEliminarTrabajador.setText("Eliminar Trabajador");
        jButtonEliminarTrabajador.setEnabled(false);
        jButtonEliminarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarTrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTrabajadoresLayout = new javax.swing.GroupLayout(jPanelTrabajadores);
        jPanelTrabajadores.setLayout(jPanelTrabajadoresLayout);
        jPanelTrabajadoresLayout.setHorizontalGroup(
            jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrabajadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSelec)
                    .addComponent(jLabelSalario)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarTrabajador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTrabajadoresLayout.setVerticalGroup(
            jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrabajadoresLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanelTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTrabajadoresLayout.createSequentialGroup()
                        .addComponent(jLabelSelec)
                        .addGap(41, 41, 41)
                        .addComponent(jLabelSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonEliminarTrabajador))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Trabajador"));

        jLabelNombre.setText("Nombre");

        jTextFieldNombre.setToolTipText("introduce solo caracteres");
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
        });

        jLabelApell.setText("Apellidos");

        jTextFieldApell.setToolTipText("introduce solo caracteres");
        jTextFieldApell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldApellKeyReleased(evt);
            }
        });

        jLabelSalBase.setText("Salario Base");

        jLabelComision.setText("Comision");

        jLabelElec.setText("Nº Electrodomesticos");

        jTextFieldSalBase.setToolTipText("introduce solo numeros");
        jTextFieldSalBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSalBaseKeyReleased(evt);
            }
        });

        jTextFieldComision.setToolTipText("introduce solo numeros");
        jTextFieldComision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldComisionKeyReleased(evt);
            }
        });

        jTextFieldElec.setToolTipText("introduce solo numeros");
        jTextFieldElec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldElecActionPerformed(evt);
            }
        });
        jTextFieldElec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldElecKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelApell, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSalBase, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelComision, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelElec, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldElec)
                    .addComponent(jTextFieldComision)
                    .addComponent(jTextFieldSalBase)
                    .addComponent(jTextFieldApell)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApell)
                    .addComponent(jTextFieldApell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalBase)
                    .addComponent(jTextFieldSalBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComision)
                    .addComponent(jTextFieldComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelElec)
                    .addComponent(jTextFieldElec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTipos.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos Trabajadores"));

        jPanelTipoT.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Trabajador"));

        jRadioButtonJP.setText("Jefe de proyecto");
        jRadioButtonJP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonJPItemStateChanged(evt);
            }
        });

        jRadioButtonTH.setText("Trabajador por Horas");
        jRadioButtonTH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTHItemStateChanged(evt);
            }
        });

        jRadioButtonMontador.setText("Trabajador Montador");
        jRadioButtonMontador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonMontadorItemStateChanged(evt);
            }
        });

        jRadioButtoncomision.setText("Trabajador a Comision");
        jRadioButtoncomision.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtoncomisionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelTipoTLayout = new javax.swing.GroupLayout(jPanelTipoT);
        jPanelTipoT.setLayout(jPanelTipoTLayout);
        jPanelTipoTLayout.setHorizontalGroup(
            jPanelTipoTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTipoTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonJP)
                    .addComponent(jRadioButtonTH)
                    .addComponent(jRadioButtonMontador)
                    .addComponent(jRadioButtoncomision))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTipoTLayout.setVerticalGroup(
            jPanelTipoTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonJP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonMontador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtoncomision))
        );

        jButtonAñadir.setText("Añadir");
        jButtonAñadir.setEnabled(false);
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar Datos");
        jButtonBorrar.setEnabled(false);
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTiposLayout = new javax.swing.GroupLayout(jPanelTipos);
        jPanelTipos.setLayout(jPanelTiposLayout);
        jPanelTiposLayout.setHorizontalGroup(
            jPanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTiposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTipoT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelTiposLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButtonAñadir)
                .addGap(18, 18, 18)
                .addComponent(jButtonBorrar)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanelTiposLayout.setVerticalGroup(
            jPanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTiposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTipoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadir)
                    .addComponent(jButtonBorrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuarchivo.setText("Archivo");
        jMenuBar1.add(jMenuarchivo);

        jMenutrabajador.setText("Trabajador");

        jMenuNuevo.setText("Nuevo");

        jMenuItemJP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemJP.setText("Jefe de proyecto");
        jMenuItemJP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJPActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemJP);

        jMenuItemTPH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTPH.setText("Travajador por Horas");
        jMenuItemTPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTPHActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemTPH);

        jMenuItemMontador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemMontador.setText("Trabajador Montador");
        jMenuItemMontador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMontadorActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemMontador);

        jMenuItemComision.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemComision.setText("Trabajador a Comision");
        jMenuItemComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComisionActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemComision);

        jMenutrabajador.add(jMenuNuevo);
        jMenutrabajador.add(jSeparator2);

        jMenuItemBorrTodo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBorrTodo.setText("Borrar Todo");
        jMenuItemBorrTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrTodoActionPerformed(evt);
            }
        });
        jMenutrabajador.add(jMenuItemBorrTodo);

        jMenuItemBorrarSeleccionado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBorrarSeleccionado.setText("Borrar Seleccionado");
        jMenuItemBorrarSeleccionado.setEnabled(false);
        jMenuItemBorrarSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarSeleccionadoActionPerformed(evt);
            }
        });
        jMenutrabajador.add(jMenuItemBorrarSeleccionado);

        jMenuItemBorrSeleccion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBorrSeleccion.setText("Borrar Seleccion");
        jMenuItemBorrSeleccion.setEnabled(false);
        jMenuItemBorrSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrSeleccionActionPerformed(evt);
            }
        });
        jMenutrabajador.add(jMenuItemBorrSeleccion);

        jMenuBar1.add(jMenutrabajador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelTipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BOTON AÑADIR
    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        jButtonBorrar.setEnabled(false);

        if (jRadioButtonJP.isSelected() == true) {
            em5 = new JefesDeProyectos(jTextFieldNombre.getText() + " ", jTextFieldApell.getText(), Double.parseDouble(jTextFieldSalBase.getText()), Integer.parseInt(jTextFieldComision.getText()));
        }

        if (jRadioButtonTH.isSelected() == true) {
            em5 = new TrabajadoresPorHoras(jTextFieldNombre.getText() + " ", jTextFieldApell.getText(), Integer.parseInt(jTextFieldSalBase.getText()), Integer.parseInt(jTextFieldComision.getText()));
        }

        if (jRadioButtonMontador.isSelected() == true) {
            em5 = new Montador(jTextFieldNombre.getText() + " ", jTextFieldApell.getText(), Integer.parseInt(jTextFieldSalBase.getText()), Integer.parseInt(jTextFieldComision.getText()));
        }

        if (jRadioButtoncomision.isSelected() == true) {
            em5 = new Vendedores(jTextFieldNombre.getText() + " ", jTextFieldApell.getText(), Integer.parseInt(jTextFieldSalBase.getText()), Double.parseDouble(jTextFieldComision.getText()), Double.parseDouble(jTextFieldElec.getText()));
        }

        jTextFieldNombre.setText(null);
        jTextFieldApell.setText(null);
        jTextFieldSalBase.setText(null);
        jTextFieldComision.setText(null);
        jTextFieldElec.setText(null);
        jButtonAñadir.setEnabled(false);
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jRadioButtonJPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonJPItemStateChanged
        ocultar();
    }//GEN-LAST:event_jRadioButtonJPItemStateChanged

    private void jRadioButtonTHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTHItemStateChanged
        ocultar();
    }//GEN-LAST:event_jRadioButtonTHItemStateChanged

    private void jRadioButtonMontadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonMontadorItemStateChanged
        ocultar();
    }//GEN-LAST:event_jRadioButtonMontadorItemStateChanged

    private void jRadioButtoncomisionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtoncomisionItemStateChanged
        ocultar();
        jButtonAñadir.setEnabled(false);
    }//GEN-LAST:event_jRadioButtoncomisionItemStateChanged

    //BOTON BORRAR
    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        jTextFieldNombre.setText(null);
        jTextFieldApell.setText(null);
        jTextFieldSalBase.setText(null);
        jTextFieldComision.setText(null);
        jTextFieldElec.setText(null);
        jButtonAñadir.setEnabled(false);
        jButtonBorrar.setEnabled(false);
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextFieldElecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldElecKeyReleased

        compr();
    }//GEN-LAST:event_jTextFieldElecKeyReleased

    private void jTextFieldElecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldElecActionPerformed

    }//GEN-LAST:event_jTextFieldElecActionPerformed

    private void jTextFieldComisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldComisionKeyReleased
        compr();
    }//GEN-LAST:event_jTextFieldComisionKeyReleased

    private void jTextFieldSalBaseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSalBaseKeyReleased
        compr();
    }//GEN-LAST:event_jTextFieldSalBaseKeyReleased

    private void jTextFieldApellKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellKeyReleased
        compr();
    }//GEN-LAST:event_jTextFieldApellKeyReleased

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased
        compr();
    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    //ELIMINAR TRABAJADOR
    private void jButtonEliminarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTrabajadorActionPerformed
        java.util.List l = jListempleados.getSelectedValuesList();
        if (l.size() == 1) {
            jButtonEliminarTrabajador.setEnabled(true);
            Empleado.modeloLista.remove(jListempleados.getSelectedIndex());
            flag = true;
        } else {
            jButtonEliminarTrabajador.setEnabled(false);
            jTextFieldSalario.setText(null);

        }
    }//GEN-LAST:event_jButtonEliminarTrabajadorActionPerformed

    private void jListempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListempleadosMouseClicked

    }//GEN-LAST:event_jListempleadosMouseClicked

    private void jTextFieldSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalarioActionPerformed

    }//GEN-LAST:event_jTextFieldSalarioActionPerformed

    private void jMenuItemTPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTPHActionPerformed
        jRadioButtonTH.setSelected(true);
    }//GEN-LAST:event_jMenuItemTPHActionPerformed

    private void jMenuItemComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComisionActionPerformed
        jRadioButtoncomision.setSelected(true);
    }//GEN-LAST:event_jMenuItemComisionActionPerformed


    private void jListempleadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListempleadosValueChanged

        java.util.List l = jListempleados.getSelectedValuesList();
        if (flag == false) {
            if (l.size() == 1) {
                em5 = (Empleado) Empleado.modeloLista.get(jListempleados.getSelectedIndex());
                jTextFieldSalario.setText(Double.toString(em5.salario()));
                jButtonEliminarTrabajador.setEnabled(true);
                jMenuItemBorrarSeleccionado.setEnabled(true);
                jMenuItemBorrSeleccion.setEnabled(false);

            } else {
                jButtonEliminarTrabajador.setEnabled(false);
                jTextFieldSalario.setText(null);
            }

            if (l.size() > 1) {
                jMenuItemBorrarSeleccionado.setEnabled(false);
                jMenuItemBorrSeleccion.setEnabled(true);
            }
        } else {
            flag = false;
        }


    }//GEN-LAST:event_jListempleadosValueChanged

    //BORRAR SELECCIONADO
    private void jMenuItemBorrarSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarSeleccionadoActionPerformed
        // java.util.List l = jListempleados.getSelectedValuesList();

        Empleado.modeloLista.remove(jListempleados.getSelectedIndex());

    }//GEN-LAST:event_jMenuItemBorrarSeleccionadoActionPerformed

    //BORRAR SELECCION
    private void jMenuItemBorrSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrSeleccionActionPerformed

        int i;
        int[] x = jListempleados.getSelectedIndices();

        for (i = x.length - 1; i >= 0; i--) {
            Empleado.modeloLista.remove(jListempleados.getSelectedIndex());
        }

    }//GEN-LAST:event_jMenuItemBorrSeleccionActionPerformed

    //BORRAR TODO
    private void jMenuItemBorrTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrTodoActionPerformed

        Empleado.modeloLista.removeAllElements();
    }//GEN-LAST:event_jMenuItemBorrTodoActionPerformed

    //NUEVO JEFE PROYECTO
    private void jMenuItemJPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJPActionPerformed
        jRadioButtonJP.setSelected(true);
    }//GEN-LAST:event_jMenuItemJPActionPerformed

    private void jMenuItemMontadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMontadorActionPerformed
        jRadioButtonMontador.setSelected(true);
    }//GEN-LAST:event_jMenuItemMontadorActionPerformed

    //COMPROBAR
    public void compr() {
        jButtonBorrar.setEnabled(true);

        if (jTextFieldElec.isVisible()) {
            if (jTextFieldNombre.getText().matches("[a-zA-Z ]+")
                    && jTextFieldApell.getText().matches("[a-zA-Z ]+")
                    && jTextFieldComision.getText().matches("[0-9.]+")
                    && jTextFieldSalBase.getText().matches("[0-9.]+")
                    && jTextFieldElec.getText().matches("[0-9.]+")) {
                jButtonAñadir.setEnabled(true);
            } else {
                jButtonAñadir.setEnabled(false);
            }

        } else {
            jButtonBorrar.setEnabled(true);
            if (jTextFieldNombre.getText().matches("[a-zA-Z ]+")
                    && jTextFieldApell.getText().matches("[a-zA-Z ]+")
                    && jTextFieldComision.getText().matches("[0-9.]+")
                    && jTextFieldSalBase.getText().matches("[0-9.]+")) {

                jButtonAñadir.setEnabled(true);

            } else {
                jButtonBorrar.setEnabled(true);

            }
        }

        if (jTextFieldNombre.getText().length() != 0) {
            if (jTextFieldNombre.getText().matches("[a-zA-Z ]+")) {
                jTextFieldNombre.setBackground(Color.WHITE);
            } else {
                jTextFieldNombre.setBackground(Color.RED);
            }
        } else {
            jTextFieldNombre.setBackground(Color.WHITE);
        }

        if (jTextFieldApell.getText().length() != 0) {
            if (jTextFieldApell.getText().matches("[a-zA-Z ]+")) {
                jTextFieldApell.setBackground(Color.WHITE);
            } else {
                jTextFieldApell.setBackground(Color.RED);
            }
        } else {
            jTextFieldApell.setBackground(Color.WHITE);
        }

        if (jTextFieldComision.getText().length() != 0) {
            if (jTextFieldComision.getText().matches("[0-9.]+")) {
                jTextFieldComision.setBackground(Color.WHITE);
            } else {
                jTextFieldComision.setBackground(Color.RED);
            }
        } else {
            jTextFieldComision.setBackground(Color.WHITE);
        }

        if (jTextFieldSalBase.getText().length() != 0) {
            if (jTextFieldSalBase.getText().matches("[0-9.]+")) {
                jTextFieldSalBase.setBackground(Color.WHITE);
            } else {
                jTextFieldSalBase.setBackground(Color.RED);
            }
        } else {
            jTextFieldSalBase.setBackground(Color.WHITE);
        }

        if (jTextFieldElec.getText().length() != 0) {
            if (jTextFieldElec.getText().matches("[0-9.]+")) {
                jTextFieldElec.setBackground(Color.WHITE);
            } else {
                jTextFieldElec.setBackground(Color.RED);
            }
        } else {
            jTextFieldElec.setBackground(Color.WHITE);
        }

    }

    public void ocultar() {

        int opc = 0;
        if (jRadioButtonJP.isSelected()) {
            opc = 1;
        }
        if (jRadioButtonTH.isSelected()) {
            opc = 2;
        }
        if (jRadioButtonMontador.isSelected()) {
            opc = 3;
        }
        if (jRadioButtoncomision.isSelected()) {
            opc = 4;
        }

        switch (opc) {
            case 1:
                jLabelNombre.setVisible(true);
                jLabelApell.setVisible(true);
                jLabelSalBase.setVisible(true);
                jLabelComision.setVisible(true);
                jLabelElec.setVisible(false);

                jTextFieldNombre.setVisible(true);
                jTextFieldApell.setVisible(true);
                jTextFieldSalBase.setVisible(true);
                jTextFieldComision.setVisible(true);
                jTextFieldElec.setVisible(false);

                jLabelSalBase.setText("Salario Base");
                jLabelComision.setText("Nº Proyectos");

                break;

            case 2:
                jLabelNombre.setVisible(true);
                jLabelApell.setVisible(true);
                jLabelSalBase.setVisible(true);
                jLabelComision.setVisible(true);
                jLabelElec.setVisible(false);

                jTextFieldNombre.setVisible(true);
                jTextFieldApell.setVisible(true);
                jTextFieldSalBase.setVisible(true);
                jTextFieldComision.setVisible(true);
                jTextFieldElec.setVisible(false);

                jLabelSalBase.setText("Nº Unidades Montadas");
                jLabelComision.setText("Salario por Unidad Montada");

                break;

            case 3:
                jLabelNombre.setVisible(true);
                jLabelApell.setVisible(true);
                jLabelSalBase.setVisible(true);
                jLabelComision.setVisible(true);
                jLabelElec.setVisible(false);

                jTextFieldNombre.setVisible(true);
                jTextFieldApell.setVisible(true);
                jTextFieldSalBase.setVisible(true);
                jTextFieldComision.setVisible(true);
                jTextFieldElec.setVisible(false);

                jLabelSalBase.setText("Nº Unidades Montadas");
                jLabelComision.setText("Salario por Unidad Montada");
                break;

            case 4:
                jLabelNombre.setVisible(true);
                jLabelApell.setVisible(true);
                jLabelSalBase.setVisible(true);
                jLabelComision.setVisible(true);
                jLabelElec.setVisible(true);

                jTextFieldNombre.setVisible(true);
                jTextFieldApell.setVisible(true);
                jTextFieldSalBase.setVisible(true);
                jTextFieldComision.setVisible(true);
                jTextFieldElec.setVisible(true);

                jLabelSalBase.setText("Salario Base");
                jLabelComision.setText("Salario por Comision");

                break;

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonEliminarTrabajador;
    private javax.swing.JLabel jLabelApell;
    private javax.swing.JLabel jLabelComision;
    private javax.swing.JLabel jLabelElec;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSalBase;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelSelec;
    private javax.swing.JList jListempleados;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBorrSeleccion;
    private javax.swing.JMenuItem jMenuItemBorrTodo;
    private javax.swing.JMenuItem jMenuItemBorrarSeleccionado;
    private javax.swing.JMenuItem jMenuItemComision;
    private javax.swing.JMenuItem jMenuItemJP;
    private javax.swing.JMenuItem jMenuItemMontador;
    private javax.swing.JMenuItem jMenuItemTPH;
    private javax.swing.JMenu jMenuNuevo;
    private javax.swing.JMenu jMenuarchivo;
    private javax.swing.JMenu jMenutrabajador;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelTipoT;
    private javax.swing.JPanel jPanelTipos;
    private javax.swing.JPanel jPanelTrabajadores;
    private javax.swing.JRadioButton jRadioButtonJP;
    private javax.swing.JRadioButton jRadioButtonMontador;
    private javax.swing.JRadioButton jRadioButtonTH;
    private javax.swing.JRadioButton jRadioButtoncomision;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTextFieldApell;
    private javax.swing.JTextField jTextFieldComision;
    private javax.swing.JTextField jTextFieldElec;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSalBase;
    private javax.swing.JTextField jTextFieldSalario;
    // End of variables declaration//GEN-END:variables

}
